// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skills.Databases;

#nullable disable

namespace Skills.Migrations
{
    [DbContext(typeof(SkillsContext))]
    [Migration("20240417081436_AddsCvMinLevel")]
    partial class AddsCvMinLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Skills.Models.AbstractSkillModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CvId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TypeId");

                    b.ToTable("AbstractSkillModel");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AbstractSkillModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Skills.Models.CV.CvCertificationInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CvId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CvInfoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.HasIndex("CvInfoId");

                    b.ToTable("CvCertifications");
                });

            modelBuilder.Entity("Skills.Models.CV.CvEducationInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CvId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CvInfoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.HasIndex("CvInfoId");

                    b.ToTable("CvEducations");
                });

            modelBuilder.Entity("Skills.Models.CV.CvExperienceInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CvId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CvInfoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.HasIndex("CvInfoId");

                    b.ToTable("CvExperiences");
                });

            modelBuilder.Entity("Skills.Models.CV.CvInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CVs");
                });

            modelBuilder.Entity("Skills.Models.CV.CvSafetyCertificationInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CvId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CvInfoId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Granted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CertId");

                    b.HasIndex("CvId");

                    b.HasIndex("CvInfoId");

                    b.ToTable("CvSafetyCertifications");
                });

            modelBuilder.Entity("Skills.Models.CV.SafetyCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SafetyCertifications");
                });

            modelBuilder.Entity("Skills.Models.GroupModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Skills.Models.SKillInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SkillsTypes");
                });

            modelBuilder.Entity("Skills.Models.SoftTypeLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SoftTypesLevels");
                });

            modelBuilder.Entity("Skills.Models.TypeLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("TypesLevels");
                });

            modelBuilder.Entity("Skills.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Skills.Models.UserSkillModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSoftSkill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UsersSkills");
                });

            modelBuilder.Entity("Skills.Models.SkillModel", b =>
                {
                    b.HasBaseType("Skills.Models.AbstractSkillModel");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CvInfoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubCategoryId")
                        .HasColumnType("TEXT");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CvId");

                    b.HasIndex("CvInfoId");

                    b.HasIndex("SubCategoryId");

                    b.HasDiscriminator().HasValue("SkillModel");
                });

            modelBuilder.Entity("Skills.Models.SoftSkillModel", b =>
                {
                    b.HasBaseType("Skills.Models.AbstractSkillModel");

                    b.Property<Guid?>("CvInfoId")
                        .HasColumnType("TEXT");

                    b.HasIndex("CvId");

                    b.HasIndex("CvInfoId");

                    b.ToTable("AbstractSkillModel", t =>
                        {
                            t.Property("CvInfoId")
                                .HasColumnName("SoftSkillModel_CvInfoId");
                        });

                    b.HasDiscriminator().HasValue("SoftSkillModel");
                });

            modelBuilder.Entity("Skills.Models.AbstractSkillModel", b =>
                {
                    b.HasOne("Skills.Models.GroupModel", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("Skills.Models.SKillInfo", "TypeInfo")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("TypeInfo");
                });

            modelBuilder.Entity("Skills.Models.CV.CvCertificationInfo", b =>
                {
                    b.HasOne("Skills.Models.CV.CvInfo", "Cv")
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skills.Models.CV.CvInfo", null)
                        .WithMany("Certifications")
                        .HasForeignKey("CvInfoId");

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("Skills.Models.CV.CvEducationInfo", b =>
                {
                    b.HasOne("Skills.Models.CV.CvInfo", "Cv")
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skills.Models.CV.CvInfo", null)
                        .WithMany("Education")
                        .HasForeignKey("CvInfoId");

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("Skills.Models.CV.CvExperienceInfo", b =>
                {
                    b.HasOne("Skills.Models.CV.CvInfo", "Cv")
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skills.Models.CV.CvInfo", null)
                        .WithMany("Experiences")
                        .HasForeignKey("CvInfoId");

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("Skills.Models.CV.CvSafetyCertificationInfo", b =>
                {
                    b.HasOne("Skills.Models.CV.SafetyCertification", "Certification")
                        .WithMany()
                        .HasForeignKey("CertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skills.Models.CV.CvInfo", "Cv")
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skills.Models.CV.CvInfo", null)
                        .WithMany("SafetyCertifications")
                        .HasForeignKey("CvInfoId");

                    b.Navigation("Certification");

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("Skills.Models.SoftTypeLevel", b =>
                {
                    b.HasOne("Skills.Models.SoftSkillModel", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Skills.Models.TypeLevel", b =>
                {
                    b.HasOne("Skills.Models.SKillInfo", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Skills.Models.UserModel", b =>
                {
                    b.HasOne("Skills.Models.GroupModel", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Skills.Models.UserSkillModel", b =>
                {
                    b.HasOne("Skills.Models.AbstractSkillModel", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skills.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skills.Models.SkillModel", b =>
                {
                    b.HasOne("Skills.Models.SKillInfo", "CategoryInfo")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skills.Models.CV.CvInfo", "Cv")
                        .WithMany()
                        .HasForeignKey("CvId");

                    b.HasOne("Skills.Models.CV.CvInfo", null)
                        .WithMany("Skills")
                        .HasForeignKey("CvInfoId");

                    b.HasOne("Skills.Models.SKillInfo", "SubCategoryInfo")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CategoryInfo");

                    b.Navigation("Cv");

                    b.Navigation("SubCategoryInfo");
                });

            modelBuilder.Entity("Skills.Models.SoftSkillModel", b =>
                {
                    b.HasOne("Skills.Models.CV.CvInfo", "Cv")
                        .WithMany()
                        .HasForeignKey("CvId");

                    b.HasOne("Skills.Models.CV.CvInfo", null)
                        .WithMany("SoftSkills")
                        .HasForeignKey("CvInfoId");

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("Skills.Models.CV.CvInfo", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Education");

                    b.Navigation("Experiences");

                    b.Navigation("SafetyCertifications");

                    b.Navigation("Skills");

                    b.Navigation("SoftSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
